site_name: CuDocs
site_url: https://docs.cutel.net
repo_url: https://github.com/cu-telecom/cutel-docs
nav:
  - Welcome: index.md
  - Events:
    - 'Electromagnetic Field 2024':
      - events/emf24/index.md
      - events/emf24/getting_started.md
      - events/emf24/telephones.md
      - events/emf24/faxing.md
      - events/emf24/bbss.md
      - events/emf24/dial_up_internet.md
      - events/emf24/viewdata.md
      - events/emf24/dsl.md
      - events/emf24/telemessage.md
      - events/emf24/dinner_bell.md
      - 'Telephone Numbers': 'events/emf24/telephone_numbers.md'
  - Technical:
    - technical/index.md
    - 'Wiring Standards': 'technical/wiring.md'
    - 'Cisco':
      - technical/cisco/vg224.md
markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - md_in_html
plugins: []
theme:
  name: material
  logo: assets/logo-light.svg
  favicon: assets/logo-dark.svg
  palette:
    primary: black
  features:
    - toc.integrate
    - navigation.top
    - navigation.indexes 
    #- navigation.expand
  custom_dir: ./overrides