site_name: CuDocs
site_url: https://docs.cutel.net
repo_url: https://github.com/cu-telecom/cutel-docs
nav:
  - Welcome: index.md
  - Getting Started: getting_started.md
  - Services:
    - services/telephones.md
    - services/faxing.md
    - services/bbss.md
    - services/dial_up_internet.md
    - services/viewdata.md
    - services/dsl.md
    - services/telemessage.md
    - services/useful_numbers.md
  - Technical:
    - technical/wiring.md
    - technical/modems.md
markdown_extensions:
  - attr_list
  - md_in_html
plugins: []
theme:
  name: material
  logo: assets/logo-light.svg
  favicon: assets/logo-dark.svg
  palette:
    primary: black
  features:
    - toc.integrate
    - navigation.top
    - navigation.expand
  custom_dir: ./overrides